# Creating first Dataframe to be used

## Importing necessary libraries

In [5]:
import pandas as pd

## Reading dataframe to be used and modified

In [6]:
original_df = pd.read_pickle('FallAllD.pkl')     # Reading original Dataset
original_df.head(10)

,SubjectID,Device,ActivityID,TrialNo,Acc,Gyr,Mag
0,1,Waist,13,1,"[[4062, -1428, -45], [4190, -1422, -24], [4302...","[[1355, 21, 159], [1334, -19, 168], [1318, -68...","[[5541, 1551, 2887], [5568, 1587, 2956], [5605..."
1,1,Waist,13,2,"[[3737, -1549, 158], [3729, -1553, 160], [3728...","[[-4, 0, -1], [-7, 11, -3], [-11, 11, -2], [-1...","[[5185, 2842, 2267], [5220, 2876, 2260], [5211..."
2,1,Waist,13,5,"[[3954, -401, -107], [3894, -346, -108], [3835...","[[177, 173, 177], [160, 183, 164], [152, 197, ...","[[5626, 2148, 3057], [5602, 2127, 3015], [5562..."
3,1,Waist,13,6,"[[3992, -682, -33], [3988, -694, -31], [3985, ...","[[12, 13, 9], [15, 12, 10], [11, 12, 9], [9, 1...","[[5530, 2536, 2713], [5521, 2561, 2774], [5493..."
4,1,Waist,13,9,"[[2223, 167, -18], [2139, 222, -90], [2108, 25...","[[-396, -163, 33], [-338, -62, 54], [-272, 44,...","[[5752, 2071, 2723], [5801, 2220, 2615], [5776..."
5,1,Waist,13,10,"[[4022, -429, 328], [4023, -428, 327], [4018, ...","[[-29, 24, 0], [-25, 22, -4], [-30, 22, -3], [...","[[5608, 2591, 2617], [5602, 2597, 2610], [5604..."
6,1,Waist,13,12,"[[4014, -227, 371], [4017, -224, 376], [4023, ...","[[-46, 15, -15], [-47, 17, -15], [-47, 22, -12...","[[5864, 1364, 3104], [5898, 1216, 3044], [5917..."
7,1,Waist,14,1,"[[3759, -283, 1472], [3760, -287, 1473], [3768...","[[1, 18, -1], [2, 15, -1], [2, 14, -2], [1, 15...","[[5631, 2366, 1215], [5657, 2305, 1174], [5624..."
8,1,Waist,14,3,"[[3962, 84, 813], [3959, 85, 814], [3956, 90, ...","[[-6, 13, 7], [-8, 14, 8], [-8, 13, 6], [-11, ...","[[5577, 837, 479], [5598, 814, 530], [5627, 93..."
9,1,Waist,14,5,"[[3590, 513, 1808], [3592, 509, 1808], [3592, ...","[[-2, 36, -4], [-4, 34, -5], [-2, 32, -5], [0,...","[[5717, 1934, 1281], [5738, 1945, 1379], [5688..."

## Adding a new column to the original dataframe

This new column is for classifying whether the row represents a fall or not. If Activity ID is greater than 100, it represents a fall.

In [9]:
dataframe1 = original_df.copy()         # Creating a copy of original datset into the variable
dataframe1['Fall'] = 0                  # Creating a new column with Fall, which become our output
for x in dataframe1.index:
    if (dataframe1.iloc[x, 2] > 100):           # Checking whether the row represents a Fall or ADL, second index refers to ActivityID
        dataframe1.iloc[x, -1] = 1              # If activity ID is above 100, the row represents a Fall
    else:
        dataframe1.iloc[x, -1] = 0              # Else, row represents a ADL

print('------------------HEAD------------------------------')
print(dataframe1.head())
print('------------------TAIL------------------------------')
print(dataframe1.tail())

------------------HEAD------------------------------
   SubjectID Device  ActivityID  TrialNo  \
0          1  Waist          13        1
1          1  Waist          13        2
2          1  Waist          13        5
3          1  Waist          13        6
4          1  Waist          13        9

                                                 Acc  \
0  [[4062, -1428, -45], [4190, -1422, -24], [4302...
1  [[3737, -1549, 158], [3729, -1553, 160], [3728...
2  [[3954, -401, -107], [3894, -346, -108], [3835...
3  [[3992, -682, -33], [3988, -694, -31], [3985, ...
4  [[2223, 167, -18], [2139, 222, -90], [2108, 25...

                                                 Gyr  \
0  [[1355, 21, 159], [1334, -19, 168], [1318, -68...
1  [[-4, 0, -1], [-7, 11, -3], [-11, 11, -2], [-1...
2  [[177, 173, 177], [160, 183, 164], [152, 197, ...
3  [[12, 13, 9], [15, 12, 10], [11, 12, 9], [9, 1...
4  [[-396, -163, 33], [-338, -62, 54], [-272, 44,...

                                                 Mag  Fall
0  [[5541, 1551, 2887], [5568, 1587, 2956], [5605...     0
1  [[5185, 2842, 2267], [5220, 2876, 2260], [5211...     0
2  [[5626, 2148, 3057], [5602, 2127, 3015], [5562...     0
3  [[5530, 2536, 2713], [5521, 2561, 2774], [5493...     0
4  [[5752, 2071, 2723], [5801, 2220, 2615], [5776...     0
------------------TAIL------------------------------
      SubjectID Device  ActivityID  TrialNo  \
1793         15  Waist         131        2
1794         15  Waist         132        1
1795         15  Waist         134        2
1796         15  Waist         135        1
1797         15  Waist         135        2

                                                    Acc  \
1793  [[3805, 827, 464], [3822, 855, 481], [3836, 80...
1794  [[4019, -542, 564], [4014, -542, 564], [4016, ...
1795  [[3884, -1500, 557], [3875, -1485, 570], [3915...
1796  [[4045, -152, 405], [4043, -143, 398], [4040, ...
1797  [[4006, -691, 18], [4010, -708, 24], [4007, -7...

                                                    Gyr  \
1793  [[125, -157, -474], [114, -161, -460], [108, -...
1794  [[-19, 18, 12], [-21, 19, 10], [-24, 16, 11], ...
1795  [[42, 42, -8], [48, 37, -4], [49, 32, -1], [57...
1796  [[21, 7, 1], [22, 7, 3], [21, 9, 5], [22, 9, 3...
1797  [[-2, 9, 6], [-5, 12, 4], [-4, 12, 5], [-8, 9,...

                                                    Mag  Fall
1793  [[2863, 617, 4182], [2891, 685, 4202], [2891, ...     1
1794  [[3567, 587, 1707], [3561, 493, 1684], [3551, ...     1
1795  [[2627, 2463, -442], [2725, 2403, -415], [2763...     1
1796  [[3521, 859, 3254], [3559, 857, 3262], [3553, ...     1
1797  [[3319, 2445, 1284], [3349, 2405, 1268], [3325...     1

## Converting data in columns and creating new pickle

Multiplying data in Acc, Gyr and Mag columns by the sensitivity of the sensor, to get the real data

Accelerometer sensitivity 0.244 mg/LSB
Angular rate sensitivity 70 mdps/LSB
Magnetic sensitivity 0.14 mgauss/LSB

In [5]:
dataframe1['Acc'] = dataframe1['Acc'] * 0.000244        # Since values are not stored with original values, this becomes useful
dataframe1['Gyr'] = dataframe1['Gyr'] * 0.07            # to modify data to become the same as another sensor used by another project
dataframe1['Mag'] = dataframe1['Mag'] * 0.00014         # so to get real data we will multiply each value by the respective sensor sensitivy

dataframe1.to_pickle('Dataframe1.pkl')

# Creating second Dataframe to be used

In [12]:
dataframe2 = dataframe1.copy()          # Creating a copy of dataframe1 into variable dataframe2
dataframe2['ADL'] = 2                   # Creating a new column for identifying ADL

for x in dataframe2.index:
    if(dataframe2.iloc[x,-2] == 1):     # Checking if Fall column is 1 or 0
        dataframe2.iloc[x,-1] = 0       # If Fall = 1, then ADL needs to be the opposite
    else:
        dataframe2.iloc[x,-1] = 1       # If Fall = 0, then ADL is equal to 1

dataframe2.to_pickle('Dataframe2.pkl')

,SubjectID,Device,ActivityID,TrialNo,Acc,Gyr,Mag,Fall,ADL
0,1,Waist,13,1,"[[4062, -1428, -45], [4190, -1422, -24], [4302...","[[1355, 21, 159], [1334, -19, 168], [1318, -68...","[[5541, 1551, 2887], [5568, 1587, 2956], [5605...",0,1
1,1,Waist,13,2,"[[3737, -1549, 158], [3729, -1553, 160], [3728...","[[-4, 0, -1], [-7, 11, -3], [-11, 11, -2], [-1...","[[5185, 2842, 2267], [5220, 2876, 2260], [5211...",0,1
2,1,Waist,13,5,"[[3954, -401, -107], [3894, -346, -108], [3835...","[[177, 173, 177], [160, 183, 164], [152, 197, ...","[[5626, 2148, 3057], [5602, 2127, 3015], [5562...",0,1
3,1,Waist,13,6,"[[3992, -682, -33], [3988, -694, -31], [3985, ...","[[12, 13, 9], [15, 12, 10], [11, 12, 9], [9, 1...","[[5530, 2536, 2713], [5521, 2561, 2774], [5493...",0,1
4,1,Waist,13,9,"[[2223, 167, -18], [2139, 222, -90], [2108, 25...","[[-396, -163, 33], [-338, -62, 54], [-272, 44,...","[[5752, 2071, 2723], [5801, 2220, 2615], [5776...",0,1

## Removing certain activities to have a better balance

The balanced dataframe contains a Fall and ADL column, with just 693 ADLs and 466 Falls.

In [28]:
balancedDataframe = dataframe2
IDtoRemove = [44,43,19,21,29,31,32,34,15,16,17,22,24,35,36,26,42,41]

for x in IDtoRemove:
    balancedDataframe.drop(balancedDataframe[balancedDataframe.ActivityID == x].index, inplace=True)    # Removing unwanted Acitivities from dataset

balancedDataframe.reset_index(drop=True, inplace=True)  # Resetting index after removing "unwanted" ADLs    
balancedDataframe.loc[balancedDataframe['ADL'] == 1].count()        # Getting the amount of ADL in the dataframe
balancedDataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1159 entries, 0 to 1158
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SubjectID   1159 non-null   int8
 1   Device      1159 non-null   object
 2   ActivityID  1159 non-null   int16
 3   TrialNo     1159 non-null   int8
 4   Acc         1159 non-null   object
 5   Gyr         1159 non-null   object
 6   Mag         1159 non-null   object
 7   Fall        1159 non-null   int64
 8   ADL         1159 non-null   int64
dtypes: int16(1), int64(2), int8(2), object(4)
memory usage: 59.0+ KB

In [29]:
balancedDataframe.to_pickle('Balanced Dataframe.pkl')   # Saving a copy of the balanced dataframe

# Creating third Dataframe to be used

This dataframe will have just 1 column, but we will be using average, std deviation and range.

In [13]:
dataframe3 = pd.read_pickle('Dataframe1.pkl')       # Reading dataframe1

# Since we are going to be using basic statistical features, we need to create new columns for each one of them
# Those features are: Mean, Standar Deviation and Range.
# We create a new column for each feature and for each axis, then we have 9 new columns for each sensor
# Totalling 9 new columns per sensor, finally creating 18 new columns
dataframe3['Mean Acc X'] = -1
dataframe3['Mean Acc Y'] = -1
dataframe3['Mean Acc Z'] = -1
dataframe3['Std Acc X'] = -1
dataframe3['Std Acc Y'] = -1
dataframe3['Std Acc Z'] = -1
dataframe3['Rng Acc X'] = -1
dataframe3['Rng Acc Y'] = -1
dataframe3['Rng Acc Z'] = -1

dataframe3['Mean Gyr X'] = -1
dataframe3['Mean Gyr Y'] = -1
dataframe3['Mean Gyr Z'] = -1
dataframe3['Std Gyr X'] = -1
dataframe3['Std Gyr Y'] = -1
dataframe3['Std Gyr Z'] = -1
dataframe3['Rng Gyr X'] = -1
dataframe3['Rng Gyr Y'] = -1
dataframe3['Rng Gyr Z'] = -1

dataframe3['Mean Mag X'] = -1
dataframe3['Mean Mag Y'] = -1
dataframe3['Mean Mag Z'] = -1
dataframe3['Std Mag X'] = -1
dataframe3['Std Mag Y'] = -1
dataframe3['Std Mag Z'] = -1
dataframe3['Rng Mag X'] = -1
dataframe3['Rng Mag Y'] = -1
dataframe3['Rng Mag Z'] = -1
''''''
for x in dataframe3.index:
    
    AccX = pd.DataFrame(dataframe3.iloc[x].Acc.tolist())[0]     # Creating a dataframe containing acceleration in X
    AccY = pd.DataFrame(dataframe3.iloc[x].Acc.tolist())[1]     # Creating a dataframe containing acceleration in Y
    AccZ = pd.DataFrame(dataframe3.iloc[x].Acc.tolist())[2]     # Creating a dataframe containing acceleration in Z
    
    GyrX = pd.DataFrame(dataframe3.iloc[x].Gyr.tolist())[0]     # Creating a dataframe containing angular velocity in X
    GyrY = pd.DataFrame(dataframe3.iloc[x].Gyr.tolist())[1]     # Creating a dataframe containing angular velocity in Y
    GyrZ = pd.DataFrame(dataframe3.iloc[x].Gyr.tolist())[2]     # Creating a dataframe containing angular velocity in Z

    MagX = pd.DataFrame(dataframe3.iloc[x].Mag.tolist())[0]     # Creating a dataframe containing magnetic field in X
    MagY = pd.DataFrame(dataframe3.iloc[x].Mag.tolist())[1]     # Creating a dataframe containing magnetic field in Y
    MagZ = pd.DataFrame(dataframe3.iloc[x].Mag.tolist())[2]     # Creating a dataframe containing magnetic field in Z

    dataframe3.iloc[x, 8] = AccX.mean()                         # Setting the value of Mean acceleration in X, Y and Z
    dataframe3.iloc[x, 9] = AccY.mean()                         
    dataframe3.iloc[x, 10] = AccZ.mean()                        
    dataframe3.iloc[x, 11] = AccX.std()                         # Setting the value of the Standard Deviation of acceleration in X, Y and Z
    dataframe3.iloc[x, 12] = AccY.std()
    dataframe3.iloc[x, 13] = AccZ.std()
    dataframe3.iloc[x, 14] = AccX.max() - AccX.min()            # Setting the value of the Range of acceleration in X, Y and Z
    dataframe3.iloc[x, 15] = AccY.max() - AccY.min()
    dataframe3.iloc[x, 16] = AccZ.max() - AccZ.min()

    dataframe3.iloc[x, 17] = GyrX.mean()                        # Setting the value of Mean angular velocity in X, Y and Z
    dataframe3.iloc[x, 18] = GyrY.mean()
    dataframe3.iloc[x, 19] = GyrZ.mean()
    dataframe3.iloc[x, 20] = GyrX.std()                         # Setting the value of the Standard Deviation of angular velocity in X, Y and Z
    dataframe3.iloc[x, 21] = GyrY.std()
    dataframe3.iloc[x, 22] = GyrZ.std()
    dataframe3.iloc[x, 23] = GyrX.max() - GyrX.min()            # Setting the value of the Range of angular velocity in X, Y and Z
    dataframe3.iloc[x, 24] = GyrY.max() - GyrY.min()
    dataframe3.iloc[x, 25] = GyrZ.max() - GyrZ.min()

    dataframe3.iloc[x, 26] = MagX.mean()                        # Setting the value of Mean magnetic field in X, Y and Z
    dataframe3.iloc[x, 27] = MagY.mean()
    dataframe3.iloc[x, 28] = MagZ.mean()
    dataframe3.iloc[x, 29] = MagX.std()                         # Setting the value of the Standard Deviation of magnetic field in X, Y and Z
    dataframe3.iloc[x, 30] = MagY.std()
    dataframe3.iloc[x, 31] = MagZ.std()
    dataframe3.iloc[x, 32] = MagX.max() - MagX.min()            # Setting the value of the Range of magnetic field in X, Y and Z
    dataframe3.iloc[x, 33] = MagY.max() - MagY.min()
    dataframe3.iloc[x, 34] = MagZ.max() - MagZ.min()
    
dataframe3.to_pickle('Dataframe with Statistical Characteristics.pkl')  # Creating a new dataframe with Statistical Characteristics

In [14]:
col = dataframe3.pop('Fall')            # Popping Fall column

dataframe3.insert(34, col.name, col)    # Rearranging columns, so Fall column will be at the end of the dataframe

dataframe3.tail()                       # Showing tail of dataframe3

dataframe3.to_pickle('Dataframe3.pkl')  # Saving dataframe3

,SubjectID,Device,ActivityID,TrialNo,Acc,Gyr,Mag,Mean Acc X,Mean Acc Y,Mean Acc Z,...,Mean Mag X,Mean Mag Y,Mean Mag Z,Std Mag X,Std Mag Y,Std Mag Z,Rng Mag X,Rng Mag Y,Rng Mag Z,Fall
1793,15,Waist,131,2,"[[0.92842, 0.201788, 0.113216], [0.932568, 0.2...","[[8.75, -10.99, -33.18], [7.98, -11.2700000000...","[[0.40081999999999995, 0.08638, 0.58548], [0.4...",0.421164,0.486860,-0.259032,...,0.255893,0.063975,0.584274,0.155849,0.054347,0.116918,0.51660,0.49532,0.92008,1
1794,15,Waist,132,1,"[[0.980636, -0.132248, 0.137616], [0.979416, -...","[[-1.33, 1.2600000000000002, 0.840000000000000...","[[0.49937999999999994, 0.08217999999999999, 0....",0.477437,-0.463409,-0.259671,...,0.413253,0.238942,0.357015,0.084351,0.155681,0.124277,0.34916,0.38920,0.64218,1
1795,15,Waist,134,2,"[[0.947696, -0.366, 0.135908], [0.9455, -0.362...","[[2.9400000000000004, 2.9400000000000004, -0.5...","[[0.36777999999999994, 0.34481999999999996, -0...",0.516297,0.216274,-0.216580,...,0.337363,0.058966,0.370667,0.181615,0.105069,0.136420,0.43820,0.41636,0.78834,1
1796,15,Waist,135,1,"[[0.98698, -0.037087999999999996, 0.0988199999...","[[1.4700000000000002, 0.49000000000000005, 0.0...","[[0.49293999999999993, 0.12025999999999999, 0....",0.838070,0.347216,0.030255,...,0.470200,0.140514,0.245743,0.021936,0.126791,0.167907,0.13300,0.35028,0.64596,1
1797,15,Waist,135,2,"[[0.977464, -0.168604, 0.004392], [0.97844, -0...","[[-0.14, 0.6300000000000001, 0.420000000000000...","[[0.46465999999999996, 0.3423, 0.1797599999999...",0.197696,-0.241964,0.443883,...,0.173890,0.317003,0.045909,0.280613,0.035531,0.091014,0.61936,0.20300,0.38052,1

# Creating fourth Dataframe to be used

This dataframe will contain all data but having 2 columns for outputs

In [24]:
dataframe4 = dataframe3.copy()              # Creating a copy of dataframe3 into variable dataframe4
dataframe4['ADL'] = -1                      # Creating a new column for ADL
for x in dataframe4.index:
    if dataframe4.iloc[x,-2] == 1:          # Checking whether Fall column is 1 or not
        dataframe4.iloc[x,-1] = 0           # If Fall column is 1, then ADL should be 0
    else:
        dataframe4.iloc[x,-1] = 1           # If Fall column is 0, then ADL should be 1

dataframe4.to_pickle('Dataframe4.pkl')      # Saving Dataframe4

# Creating fifth Dataframe to be used

This dataframe will contain only basic statistical features of acceleration

In [26]:
dataframe5 = dataframe3.copy()              # Creating a copy of dataframe3 into variable dataframe5
#columnsToDrop = ['Mean Gyr X', 'Mean Gyr Y', 'Mean Gyr Z','Std Gyr X', 'Std Gyr Y', 'Std Gyr Z', 'Rng Gyr X', 'Rng Gyr Y', 'Rng Gyr Z',
 #                'Mean Mag X', 'Mean Mag Y', 'Mean Mag Z','Std Mag X', 'Std Mag Y', 'Std Mag Z', 'Rng Mag X', 'Rng Mag Y', 'Rng Mag Z']
# The columns above are the ones that need to be dropped for creating dataframe5

columnsToDrop = range(16, 34)       # Dropping column by its indexes
dataframe5.drop(dataframe5.columns[columnsToDrop], axis=1, inplace=True)    # dropping columns and modifying current variable

dataframe5.tail()
#dataframe5.to_pickle('Dataframe5.pkl')  # Saving datadrame5

,SubjectID,Device,ActivityID,TrialNo,Acc,Gyr,Mag,Mean Acc X,Mean Acc Y,Mean Acc Z,Std Acc X,Std Acc Y,Std Acc Z,Rng Acc X,Rng Acc Y,Rng Acc Z,Fall
1793,15,Waist,131,2,"[[0.92842, 0.201788, 0.113216], [0.932568, 0.2...","[[8.75, -10.99, -33.18], [7.98, -11.2700000000...","[[0.40081999999999995, 0.08638, 0.58548], [0.4...",0.421164,0.486860,-0.259032,0.482082,0.413782,0.403274,3.109536,6.272264,7.321708,1
1794,15,Waist,132,1,"[[0.980636, -0.132248, 0.137616], [0.979416, -...","[[-1.33, 1.2600000000000002, 0.840000000000000...","[[0.49937999999999994, 0.08217999999999999, 0....",0.477437,-0.463409,-0.259671,0.525878,0.407719,0.456425,12.972016,11.122984,14.119792,1
1795,15,Waist,134,2,"[[0.947696, -0.366, 0.135908], [0.9455, -0.362...","[[2.9400000000000004, 2.9400000000000004, -0.5...","[[0.36777999999999994, 0.34481999999999996, -0...",0.516297,0.216274,-0.216580,0.416558,0.605298,0.381468,5.058364,3.708556,6.397192,1
1796,15,Waist,135,1,"[[0.98698, -0.037087999999999996, 0.0988199999...","[[1.4700000000000002, 0.49000000000000005, 0.0...","[[0.49293999999999993, 0.12025999999999999, 0....",0.838070,0.347216,0.030255,0.210071,0.364009,0.147526,4.985652,3.778584,5.548072,1
1797,15,Waist,135,2,"[[0.977464, -0.168604, 0.004392], [0.97844, -0...","[[-0.14, 0.6300000000000001, 0.420000000000000...","[[0.46465999999999996, 0.3423, 0.1797599999999...",0.197696,-0.241964,0.443883,0.779496,0.292070,0.428101,13.737444,10.731608,7.271688,1

# Creating sixth Dataframe to be used

This dataframe will contain only basic statistical features of acceleration and it will have 2 columns for output.

In [30]:
dataframe6 = dataframe5.copy()              # Creating a copy of dataframe5 into dataframe6
dataframe6['ADL'] = 2                       # Creating a new column for ADL

for x in dataframe6.index:
    if(dataframe6.iloc[x, -2] == 1):        # Checking whether Fall is 1 or 0
        dataframe6.iloc[x, -1] = 0          # If Fall column is 1, then ADL needs to be 0
    else:
        dataframe6.iloc[x, -1] = 1          # If Fall column is 0, then ADL needs to be 1

dataframe6.tail()                           # Showing the first/last 5 rows of dataframe
dataframe6.to_pickle('Dataframe6.pkl')      # Saving dataframe6